#@ GLOBALS
subcommand_use = "musisz uÅ¼yÄ‡ subkomendy"
embed_footer = "wywoÅ‚ane przez {user}"
not_accessible = "nie znaleziono"
no_reason = "nie podano powodu"

#@ ERRORS
[errors.cooldown]
title = "cooldown"
description = "musisz poczekaÄ‡ {seconds} sekund przed ponownym uÅ¼yciem tej komendy"

[errors.commands]
title = "bÅ‚Ä…d podczas wykonywania komendy"
description = "bÅ‚Ä…d zostaÅ‚ zgÅ‚oszony do twÃ³rcÃ³w bota. Przepraszamy za niedogodnoÅ›ci."
description_with_error = "bÅ‚Ä…d zostaÅ‚ zgÅ‚oszony do twÃ³rcÃ³w bota. Przepraszamy za niedogodnoÅ›ci.\n\n```rust\n{error}```"

[errors.arguments]
too_few = "podano za maÅ‚o argumentÃ³w"
too_many = "podano za duÅ¼o argumentÃ³w"
title = "bÅ‚Ä…d podczas konwersji argumentÃ³w"
member = "nie znaleziono uÅ¼ytkownika na serwerze"
guild = "nie znaleziono serwera"
channel = "nie znaleziono kanaÅ‚u"
role = "nie znaleziono roli"
emoji = "nie znaleziono emoji"
user = "nie znaleziono uÅ¼ytkownika"
guild_channel = "nie znaleziono kanaÅ‚u na serwerze"
color = "niepoprawny kolor"
duration = "niepoprawny format czasu, lub czas poniÅ¼ej 1 minuty (przykÅ‚ad: 1d2h3m4s)"
number = "niepoprawny format liczby"
bool = "niepoprawny format (oczekiwano true/false/yes/no)"
choice = "niepoprawny wybÃ³r"

[errors.missing_user_permissions]
title = "brak uprawnieÅ„"
description = "nie posiadasz uprawnieÅ„ do wykonania tej komendy"
description_detailed = "nie posiadasz uprawnieÅ„ do wykonania tej komendy; potrzebujesz uprawnieÅ„:\n\n{permissions}"

[errors.missing_bot_permissions]
title = "brak uprawnieÅ„"
description_detailed = "bot nie posiada uprawnieÅ„ do wykonania tej komendy; potrzebuje uprawnieÅ„:\n\n{permissions}"

[errors.nsfw]
title = "ostrzeÅ¼enie"
description = "ta komenda moÅ¼e byÄ‡ uÅ¼ywana tylko na kanaÅ‚ach NSFW"

#@ BOOLEANS
[bool]
"true" = "tak"
"false" = "nie"

#@ COMMAND DESCRIPTIONS
[command_description]
services = "zarzÄ…dzaj usÅ‚ugami bota"
tempmute = "wycisz uÅ¼ytkownika na okreÅ›lony czas"
unmute = "usuÅ„ wyciszenie uÅ¼ytkownika na serwerze"
mute = "klasycznie wycisz uÅ¼ytkownika na serwerze"
config = "zarzÄ…dzaj konfiguracjÄ… bota"
untimeout = "usuÅ„ wyciszenie uÅ¼ytkownika na serwerze"
timeout = "wycisz uÅ¼ytkownika na serwerze, na 28 dni (limit Discorda)"
warn = "ostrzeÅ¼ uÅ¼ytkownika"
punishment = "wyÅ›wietl listÄ™ kar uÅ¼ytkownika"
tempban = "zbanuj uÅ¼ytkownika na okreÅ›lony czas"
kick = "wyrzuÄ‡ uÅ¼ytkownika z serwera"
ban = "zbanuj uÅ¼ytkownika na serwerze"
theme = "zarzÄ…dzaj wyglÄ…dem bota"
prefix = "zarzÄ…dzaj prefixami bota"
help = "wyÅ›wietla listÄ™ komend"
ping = "sprawdÅº ping bota"
shell = "wykonaj kod w konsoli"
ascii_art = "wyÅ›wietl tekst jako ASCII art"
user = "wyÅ›wietl informacje o uÅ¼ytkowniku"
stats = "wyÅ›wietl statystyki bota"
channel = "wyÅ›wietl informacje o kanale"
role = "wyÅ›wietl informacje o roli"
server = "wyÅ›wietl informacje o serwerze"
delete_punishment = "usuÅ„ karÄ™"

#@ COMMAND NAMES
[command_name]
services = "usÅ‚ugi"
tempmute = "tempmute"
unmute = "classic-unmute"
mute = "classic-mute"
config = "config"
warn = "warn"
timeout = "wycisz"
untimeout = "odcisz"
delete_punishment = "usuÅ„-karÄ™"
punishment = "punishment"
tempban = "tempban"
kick = "kick"
ban = "ban"
theme = "motyw"
help = "pomoc"
ping = "ping"
shell = "shell"
user = "uÅ¼ytkownik"
stats = "statystyki"
channel = "kanaÅ‚"
server = "serwer"
role = "rola"
ascii_art = "ascii-art"
prefix = "prefiks"

#@ SUBCOMMAND NAMES
[subcommand_name.services]
enable = "wÅ‚Ä…cz"
disable = "wyÅ‚Ä…cz"
show = "wyÅ›wietl"

[subcommand_name.config]
mute_role = "rola-wyciszenia"
show = "wyÅ›wietl"

[subcommand_name.prefix]
add = "dodaj"
remove = "usuÅ„"
list = "list"

[subcommand_name.theme]
success = "success"
warning = "warning"
info = "info"
error = "error"

#@ SUBCOMMAND DESCRIPTIONS
[subcommand_description.services]
enable = "wÅ‚Ä…cz usÅ‚ugÄ™ bota"
disable = "wyÅ‚Ä…cz usÅ‚ugÄ™ bota"
show = "wyÅ›wietl listÄ™ usÅ‚ug bota"

[subcommand_description.config]
mute_role = "ustaw rolÄ™ wyciszenia"
show = "wyÅ›wietl konfiguracjÄ™ bota"

[subcommand_description.prefix]
add = "dodaj prefix"
remove = "usuÅ„ prefix"
list = "wyÅ›wietl listÄ™ prefixÃ³w"

[subcommand_description.theme]
success = "zmieÅ„ kolor embeda, gdy operacja siÄ™ powiedzie"
warning = "zmieÅ„ kolor embeda, gdy operacja zwrÃ³ci ostrzeÅ¼enie"
info = "zmieÅ„ kolor embeda, gdy operacja zwrÃ³ci informacjÄ™"
error = "zmieÅ„ kolor embeda, gdy operacja siÄ™ nie powiedzie"

#@ PARAM DESCRIPTIONS
[param_description.services]
service_name = "nazwa usÅ‚ugi"

[param_description.theme]
color = "kolor"

[param_description.warn]
user = "uÅ¼ytkownik"
reason = "powÃ³d ostrzeÅ¼enia"

[param_description.punishment]
punishment_id = "ID kary"

[param_description.delete_punishment]
punishment_id = "ID kary"

[param_description.config]
role = "rola wyciszenia"

[param_description.tempban]
user = "uÅ¼ytkownik, ktÃ³rego chcesz zbanowaÄ‡"
duration = "czas, na jaki chcesz zbanowaÄ‡ uÅ¼ytkownika"
days = "dni do usuniÄ™cia wiadomoÅ›ci"
reason = "powÃ³d bana"

[param_description.tempmute]
user = "uÅ¼ytkownik, ktÃ³rego chcesz wyciszyÄ‡"
duration = "czas, na jaki chcesz wyciszyÄ‡ uÅ¼ytkownika"
reason = "powÃ³d wyciszenia"

[param_description.timeout]
user = "uÅ¼ytkownik, ktÃ³rego chcesz wyciszyÄ‡"
reason = "powÃ³d wyciszenia"

[param_description.unmute]
user = "uÅ¼ytkownik, ktÃ³rego chcesz odciszyÄ‡"
reason = "powÃ³d odciszenia"

[param_description.mute]
user = "uÅ¼ytkownik, ktÃ³rego chcesz wyciszyÄ‡"
reason = "powÃ³d wyciszenia"

[param_description.untimeout]
user = "uÅ¼ytkownik, ktÃ³rego chcesz odciszyÄ‡"
reason = "powÃ³d odciszenia"

[param_description.kick]
user = "uÅ¼ytkownik, ktÃ³rego chcesz wyrzuciÄ‡"
reason = "powÃ³d wyrzucenia"

[param_description.ban]
user = "uÅ¼ytkownik, ktÃ³rego chcesz zbanowaÄ‡"
reason = "powÃ³d bana"
days = "dni do usuniÄ™cia wiadomoÅ›ci"

[param_description.prefix]
prefix = "prefiks, ktÃ³ry chcesz dodaÄ‡/usunÄ…Ä‡"

[param_description.help]
command_name = "komenda"

[param_description.shell]
code = "kod do wykonania"

[param_description.user]
user = "uÅ¼ytkownik, ktÃ³rego informacje chcesz wyÅ›wietliÄ‡"

[param_description.ascii_art]
text = "tekst, ktÃ³ry chcesz wyÅ›wietliÄ‡ jako ASCII art"

[param_description.role]
role = "rola, ktÃ³rej informacje chcesz wyÅ›wietliÄ‡"

[param_description.channel]
channel = "kanaÅ‚, ktÃ³rego informacje chcesz wyÅ›wietliÄ‡"

[param_description.server]
server = "serwer, ktÃ³rego informacje chcesz wyÅ›wietliÄ‡"

#@ PARAM NAMES
[param_name.services]
service_name = "usÅ‚uga"

[param_name.punishment]
punishment_id = "id_kary"

[param_name.delete_punishment]
punishment_id = "id_kary"

[param_name.tempban]
user = "uÅ¼ytkownik"
reason = "powÃ³d"
duration = "czas"
days = "dni"

[param_name.config]
role = "rola_wyciszenia"

[param_name.tempmute]
user = "uÅ¼ytkownik"
reason = "powÃ³d"
duration = "czas"

[param_name.ban]
user = "uÅ¼ytkownik"
reason = "powÃ³d"
days = "dni"

[param_name.timeout]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.unmute]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.untimeout]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.kick]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.mute]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.warn]
user = "uÅ¼ytkownik"
reason = "powÃ³d"

[param_name.prefix]
prefix = "prefiks"

[param_name.theme]
color = "kolor"

[param_name.help]
command_name = "komenda"

[param_name.user]
user = "uÅ¼ytkownik"

[param_name.channel]
channel = "kanaÅ‚"

[param_name.server]
server = "serwer"

[param_name.ascii_art]
text = "tekst"

[param_name.stats]
stats = "statystyki"

[param_name.role]
role = "rola"

[param_name.shell]
code = "kod"

#@ GLOBALS
[globals]
error = "bÅ‚Ä…d"
success = "sukces"
info = "informacja"
warn = "ostrzeÅ¼enie"

#@ EMBED TITLES
[embed_title]
ping = "ping bota"
help = "lista komend"
shell = "wykonano kod"
user = "informacje o uÅ¼ytkowniku"
channel = "informacje o kanale"
stats = "statystyki bota"
role = "informacje o roli"
server = "informacje o serwerze"
shell_error = "bÅ‚Ä…d podczas wykonywania kodu"
theme_updated = "motyw zaktualizowany"
kick = "wyrzucono uÅ¼ytkownika"
ban = "zbanowano uÅ¼ytkownika"
tempban = "zbanowano uÅ¼ytkownika tymczasowo"
warn = "dodano ostrzeÅ¼enie uÅ¼ytkownikowi"
punishment = "lista kar uÅ¼ytkownika"
delete_punishment = "usuniÄ™to karÄ™"
confirmation = "potwierdzenie"
timeout = "dodano przerwÄ™ uÅ¼ytkownikowi"
untimeout = "usuniÄ™to przerwÄ™ uÅ¼ytkownikowi"
mute = "wyciszono uÅ¼ytkownika"
unmute = "odciszono uÅ¼ytkownika"
tempmute = "wyciszono uÅ¼ytkownika tymczasowo"

[embed_title.services]
display = "usÅ‚ugi"
enabled = "wÅ‚Ä…czono usÅ‚ugÄ™"
disabled = "wyÅ‚Ä…czono usÅ‚ugÄ™"

[embed_title.config]
show = "konfiguracja bota"
mute_role = "zmieniono rolÄ™ wyciszenia"

[embed_title.prefix]
add_success = "dodano prefix"
remove_success = "usuniÄ™to prefix"
list = "lista prefixÃ³w"

#@ COMMAND SPECIFIC DATA
[help]
general = "lista komend"
command_not_found = "nie znaleziono komendy '{command}'"

[help.with_command]
description = "informacje o komendzie {command}"
subcommands = "subcommands"
usage = "sposÃ³b uÅ¼ycia"
category = "kategoria"
aliases = "aliasy"

[ping]
pinging = "pingowanie bota..."
bot_latency = "ping bota: {latency}ms"

[user]
id = "id"
username = "nazwa uÅ¼ytkownika"
bot = "jest botem?"
created_at = "data utworzenia konta"
joined_at = "data doÅ‚Ä…czenia do serwera"
nick = "pseudonim"
roles = "lista rÃ³l"
no_nick = "brak pseudonimu"
no_roles = "brak rÃ³l"

[channel]
invalid_type = "niewspierany typ kanaÅ‚u"
id = "id"
name = "nazwa"
category = "kategoria"
created_at = "data utworzenia"
nsfw = "kanaÅ‚ NSFW?"
type = "typ"
no_category = "brak kategorii"
topic = "temat"
no_topic = "brak tematu"

[channel.types]
text = "tekstowy"
voice = "gÅ‚osowy"
category = "kategoria"
news = "ogÅ‚oszeniowy"
forum = "forum"
news_thread = "wÄ…tek ogÅ‚oszeniowy"
public_thread = "wÄ…tek publiczny"
private_thread = "wÄ…tek prywatny"
stage = "kanaÅ‚ podium"
directory = "katalog"

[role]
id = "id"
name = "nazwa"
color = "kolor"
hoist = "wyÅ›wietlana oddzielnie?"
position = "pozycja"
mentionable = "moÅ¼na oznaczyÄ‡?"
managed = "zarzÄ…dzana?"
created_at = "data utworzenia"

[server]
name = "nazwa"
id = "id"
owner = "wÅ‚aÅ›ciciel"
members = "liczba czÅ‚onkÃ³w"
roles = "liczba rÃ³l"
channels = "liczba kanaÅ‚Ã³w"
emojis = "liczba emoji"
created_at = "data utworzenia"

[stats]
version = "wersja"
uptime = "bot dziaÅ‚a od"
guilds = "serwery"
users = "uÅ¼ytkownicy"
channels = "kanaÅ‚y"
commands = "komendy"
memory = "pamiÄ™Ä‡"
system = "system"

[ascii_art]
no_result = "brak wyniku; tekst nie zawiera znakÃ³w ASCII"
too_long = "tekst ASCII jest za dÅ‚ugi"

[prefix]
add_success = "dodano prefix"
remove_success = "usuniÄ™to prefix"
add_error = "bÅ‚Ä…d podczas dodawania prefixu"
remove_error = "bÅ‚Ä…d podczas usuwania prefixu"
already_added = "ten prefix juÅ¼ istnieje"
not_found = "nie znaleziono prefixu"
list = "lista prefixÃ³w"

[theme]
color_change_success = "zmieniono kolor embeda"
color_change_error = "nie udaÅ‚o siÄ™ zmieniÄ‡ koloru embeda"

[kick]
success_description = "wyrzucono uÅ¼ytkownika {user} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ wyrzuciÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na wyrzuciÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
self = "nie moÅ¼na wyrzuciÄ‡ siebie"
bot = "nie mogÄ™ wyrzuciÄ‡ samego siebie ğŸ¥²"

[timeout]
success_description = "wyciszono uÅ¼ytkownika {user} **NA 28 DNI (limit Discorda)** z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ wyciszyÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na wyciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
administrator = "nie moÅ¼na wyciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ ma on uprawnienia administratora"
already_timeouted = "ten uÅ¼ytkownik jest juÅ¼ wyciszony"
self = "nie moÅ¼na wyciszyÄ‡ siebie"
bot = "nie mogÄ™ wyciszyÄ‡ samego siebie ğŸ¥²"

[mute]
no_mute_role = "nie znaleziono roli wyciszenia, sprawdÅº konfiguracjÄ™ bota"
success_description = "wyciszono uÅ¼ytkownika {user} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ wyciszyÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na wyciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
already_muted = "ten uÅ¼ytkownik jest juÅ¼ wyciszony"
self = "nie moÅ¼na wyciszyÄ‡ siebie"
bot = "nie mogÄ™ wyciszyÄ‡ samego siebie ğŸ¥²"

[untimeout]
success_description = "odciszono uÅ¼ytkownika {user} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ odciszyÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na odciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
not_timeouted = "ten uÅ¼ytkownik nie jest wyciszony"
self = "nie jesteÅ› wyciszony."
bot = "nie jestem wyciszony."

[unmute]
no_mute_role = "nie znaleziono roli wyciszenia, sprawdÅº konfiguracjÄ™ bota"
success_description = "odciszono uÅ¼ytkownika {user} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ odciszyÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na odciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
not_muted = "ten uÅ¼ytkownik nie jest wyciszony"
self = "nie jesteÅ› wyciszony."
bot = "nie jestem wyciszony."

[warn]
success_description = "dodano ostrzeÅ¼enie uÅ¼ytkownikowi {user} z powodem: {reason}"
highest_role = "nie moÅ¼na ostrzec uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
self = "nie moÅ¼na ostrzec siebie"
bot = "nie mogÄ™ ostrzec samego siebie ğŸ¥²"

[ban]
success_description = "zbanowano uÅ¼ytkownika {user} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ zbanowaÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
highest_role = "nie moÅ¼na zbanowaÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
self = "nie moÅ¼na zbanowaÄ‡ siebie"
bot = "nie mogÄ™ zbanowaÄ‡ samego siebie ğŸ¥²"
already_banned = "ten uÅ¼ytkownik jest juÅ¼ zbanowany"
days_error = "iloÅ›Ä‡ dni musi byÄ‡ liczbÄ… caÅ‚kowitÄ…, pomiÄ™dzy 0 a 7"

[tempban]
success_description = "zbanowano uÅ¼ytkownika {user} tymczasowo na {duration} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ tymczasowo zbanowaÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
invalid_duration = "moÅ¼esz zbanowaÄ‡ uÅ¼ytkownika na maksymalnie 1 rok"
highest_role = "nie moÅ¼na zbanowaÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
self = "nie moÅ¼na zbanowaÄ‡ siebie"
bot = "nie mogÄ™ zbanowaÄ‡ samego siebie ğŸ¥²"

[tempmute]
success_description = "tymczasowo wyciszono uÅ¼ytkownika {user} na {duration} z powodem: {reason}"
error_description = "nie udaÅ‚o siÄ™ tymczasowo wyciszyÄ‡ tego uÅ¼ytkownika, sprawdÅº uprawnienia bota"
no_mute_role = "nie znaleziono roli wyciszenia, sprawdÅº konfiguracjÄ™ bota"
invalid_duration = "moÅ¼esz wyciszyÄ‡ uÅ¼ytkownika na maksymalnie 1 rok"
already_muted = "ten uÅ¼ytkownik jest juÅ¼ wyciszony"
highest_role = "nie moÅ¼na wyciszyÄ‡ uÅ¼ytkownika, poniewaÅ¼ jego rola jest wyÅ¼sza lub taka sama jak twoja"
self = "nie moÅ¼na wyciszyÄ‡ siebie"
bot = "nie mogÄ™ wyciszyÄ‡ samego siebie ğŸ¥²"

[punishment]
info_description = "informacje o karze #{id}"
not_found = "nie znaleziono kary o id {id}"
delete_confirmation = "czy na pewno chcesz usunÄ…Ä‡ tÄ™ karÄ™?"
not_allowed = "nie masz uprawnieÅ„ do wyÅ›wietlenia tej kary; aby widzieÄ‡ kary innych uÅ¼ytkownikÃ³w, musisz mieÄ‡ uprawnienia do zarzÄ…dzania czÅ‚onkami"

[punishment.info_fields]
punishment_id = "id kary"
punishment_type = "typ kary"
reason = "powÃ³d kary"
user_id = "id uÅ¼ytkownika"
moderator_id = "id moderatora"
created_at = "data naÅ‚oÅ¼enia kary"

[confirmation]
instructions_title = "instrukcja"
instructions_description = "aby potwierdziÄ‡ swÃ³j wybÃ³r, wybierz reakcjÄ™ {correct}."
invalid_reaction = "wybrano nieprawidÅ‚owÄ… reakcjÄ™"

[delete_punishment]
success_description = "usuniÄ™to karÄ™ o ID #{id}"

[config.embed_field]
mute_role = "rola wyciszenia"

[config.mute_role]
everyone = "podaj innÄ… rolÄ™ niÅ¼ @\u200beveryone"
managed = "podaj innÄ… rolÄ™ niÅ¼ zarzÄ…dzana przez bota"
success = "zmieniono rolÄ™ wyciszenia"
error = "nie udaÅ‚o siÄ™ zmieniÄ‡ roli wyciszenia"

[services]
details = "wÅ‚Ä…czona: {enabled}\ndziaÅ‚a od {uptime}\nuruchamiana co **{interval}** sekund"
enabled = "pomyÅ›lnie wÅ‚Ä…czono usÅ‚ugÄ™"
disabled = "pomyÅ›lnie wyÅ‚Ä…czono usÅ‚ugÄ™"
not_found = "nie znaleziono tej usÅ‚ugi"